# Generated by Django 2.1.1 on 2018-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mailclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.FileField(default='', upload_to='attachments/'),
        ),
    ]
